import tweetprofil from '../images/Profile.png'
import image1 from '../images/image 1.png'
import tweetphoto from '../images/tweet-photo.png'
import ortiz from '../images/profile-photo.png'
 export const currentUser= [
    {
      userId: 0,
      avatar: ortiz,
      userName: "Brandley Ortiz",
      banner: ortiz,
      lienProfil: "@brandley",
      description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit...",
      points: "...",
      linkWeb: "brandley.com",
      dateCreated: "A rejoint Twitter en février 2001",
      abonnemets: 4086,
      abonne: "100 M",
      suiviPar: "Suivi par Benito et Matthieu Nzing",
      isLogin: true,
    },
    {
      userId: 1,
      avatar: tweetprofil,
      userName: "CNN",
      banner: tweetprofil,
      lienProfil: "@CNN",
      description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit...",
      points: "...",
      linkWeb: "cnn.com",
      dateCreated: "A rejoint Twitter en février 2007",
      abonnemets: 1086,
      abonne: "62 M",
      suiviPar: "Suivi par Benito et PlayStation",
      isLogin: false,
    },
    {
      userId: 2,
      avatar: image1,
      userName: "The New York Times",
      banner: image1,
      lienProfil: "@nytimes",
      description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit...",
      points: "...",
      linkWeb: "nytimes.com",
      dateCreated: "A rejoint Twitter en février 2012",
      abonnemets: 2086,
      abonne: "72 M",
      suiviPar: "Suivi par Matthieu et Ligue des champions",
      isLogin: false,
    },
    {
      userId: 3,
      avatar: tweetphoto,
      userName: "Twitter",
      banner: tweetphoto,
      lienProfil: "@Twitter",
      description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit...",
      points: "...",
      linkWeb: "twitter.com",
      dateCreated: "A rejoint Twitter en février 2005",
      abonnemets: 9850,
      abonne: "995 M",
      suiviPar: "Suivi par Sacre et Sylvin",
      isLogin: false,
    }
  ]